### ISSUE TITLE
mimerender-cookiecutter using React

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/mimerender-cookiecutter#2]
I have [a branch on my fork](https://github.com/gnestor/mimerender-cookiecutter/tree/react) that is a cookiecutter for creating a mime type renderer using React. It's possible to use cookiecutter to clone a branch of a repo using `cookiecutter https://github.com/jupyterlab/mimerender-cookiecutter --checkout react`. Should we create a separate repo for this cookiecutter or link to it from master's README?

**Comment by jasongrout** [comment]
Huh, I didn't realize it was easy to check out a branch. We've talked before about how to maintain small variants, but didn't come to any conclusions.

**Comment by gnestor** [comment]
This seems to be a pretty good solution. See the [react branch](https://github.com/jupyterlab/mimerender-cookiecutter/tree/react) for an example implementation.
