### ISSUE TITLE
Add more things to .gitignore

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/mimerender-cookiecutter#39]
When doing development with these repos, there are things that should be in the .gitignore (index.js, index.js.map, npm-debug.log, lib)

**Comment by gnestor** [comment]
This [.gitignore](https://github.com/jupyterlab/mimerender-cookiecutter/blob/master/%7B%7Bcookiecutter.extension_name%7D%7D/.gitignore) already covers all the build artifacts, but I noticed that jupyterlab_vega and jupyterlab_geojson both have some remnants that are being tracked. We can try a `git filter-branch -f --tree-filter 'rm -rf ./jupyterlab_vega/static' HEAD` to remove those files from the git history, but this can cause weird conflicts between branches. I think it's best to do when there are no outstanding PRs...

**Comment by gnestor** [comment]
I created an issue on jupyterlab_vega: https://github.com/altair-viz/jupyterlab_vega/issues/21

Closing this...
